### ISSUE TITLE
scrollbar repositions the page

### ISSUE THREAD

**Issue by randysim** [stuysu/epsilon#117]
On the admin page, the last module has a scrollbar while the rest don't and the scrollbar causes a shift, so I added

```css
@supports (scrollbar-gutter: stable) {
    html {
      overflow-y: auto;
      scrollbar-gutter: stable;
    }
}
```

to index.css

HOWEVER, when I add that, the NavBar (sidebar) component causes the home page to shift.

Is there really no good way?
